const SECTIONS = {
  "Node.js": `# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.npm
.yarn/cache
.pnp.*
dist/
build/
.next/
.nuxt/
.svelte-kit/
.output/
.vercel/
`,

  Python: `# Python
__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
venv/
.venv/
*.egg
.pytest_cache/
htmlcov/
`,

  Go: `# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
go.work
vendor/
`,

  Rust: `# Rust
target/
Cargo.lock
**/*.rs.bk
`,

  macOS: `# macOS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
`,

  Windows: `# Windows
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
`,

  Linux: `# Linux
*~
.fuse_hidden*
.Trash-*
.nfs*
`,

  JetBrains: `# JetBrains
.idea/
*.iml
*.iws
*.ipr
`,

  "VS Code": `# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
`,

  "Environment files": `# Environment
.env
.env.*
!.env.example
*.pem
*.key
`,
};

export function getGitignoreTemplate(selections) {
  let content = "# Generated by sgomez-cli\n\n";

  for (const sel of selections) {
    if (SECTIONS[sel]) {
      content += SECTIONS[sel] + "\n";
    }
  }

  // Always include logs and coverage
  content += `# Logs
logs/
*.log

# Coverage
coverage/
*.lcov

# Misc
.cache/
tmp/
temp/
`;

  return content;
}
